### ISSUE TITLE
Group all parameters needed for embedded power flow computations

### ISSUE THREAD

**Issue by casella** [PowerGrids/PowerGrids#101]
PowerGrids 2.0.0 will feature an optional embedded power flow computation, to get the start values of voltage and power on the ports. This feature requires some parameters, that only need to be set if the embedded power flow is actually used, otherwise they can be left at their default values and will be ignored.

I would recommend to add the `annotation(Dialog(group = "Embedded power flow"), enable = computePF)` to all such parameters, so that they are easily identified, and automatically greyed out when they are not required.

**Comment by AndreaBartolini** [comment]
Implemented by pr #97 and #100
