### ISSUE TITLE
Conversion of loads unclear 

### ISSUE THREAD

**Issue by ceraolo** [PowerGrids/PowerGrids#117]
In the system object mask I see the variable loadLowVoltageAsImpedance.

I know what is behind this, since I partecipated at the definition of the behaviour.
Nevertheless, as a user I find this very difficult to understand:
1. the system object info does not say anything about this
2. probabily something is written in the tutorial, but the tutorial is large and complex, and it is not easy to find spot pieces of info, without a link from where they are needed.y

I propose to write something in the system object info, with a possible link to other parts in the documentation where maibe further details are added.
Maybe it is sufficient just to say what the "low-voltage conditions" to determine the load swich into fixed impedances are. AFAICR it is just a voltage threshold. Probably just this needs to be said, and and whether this threshold is fixed or can be changed by the library user.

**Comment by casella** [comment]
Changed the comment of `loadLowVoltageAsImpedance` to 

> "= true, all loads work as fixed impedances below their VPuThr voltage threshold".
