### ISSUE TITLE
Misplaced transformer name label

### ISSUE THREAD

**Issue by ceraolo** [PowerGrids/PowerGrids#148]
Transformer name label is misplaced. good position is centered as is for line, but for transformers it is not:
![image](https://github.com/PowerGrids/PowerGrids/assets/7373030/bb2c43d2-0190-4031-9ccd-9a855a1f1c32)

This seems a minor glitch, but with cluttered diagrams, ad usually power grids' are, it creates a lot of problems.

This issue occurs with develop branch downloaded 10 March 2024

**Comment by AndreaBartolini** [comment]
Fixed by PR #149
