### ISSUE TITLE
Simple possible improvement

### ISSUE THREAD

**Issue by max-privato** [PowerGrids/PowerGrids#23]
@adriguir 
I'm planning to use PowerGrids as a tool for University courses, so I tend to evaluate it also with the student's eyes in mind.  That's Why I'm proposing this ticket related to a minor issue, whose solution, however, would clarify and simplify the use of the component.

Regarding EquivalentGrid, I wonder why the c-factor for calculation of short-circuit capacity is introduced.
The equation in which it is used is:
``` 
final parameter Types.ComplexPower Ssc=ComplexMath.fromPolar(SSC/c, atan(1/
      R_X)) ;
```
It seems to me that this parameter could be omitted, thus simplifying the component dialog box, which is rather rich in parameters.

Moreover, I would suggest, in the documentation of this component, to substitute 
`The impedance is computed to provide a power flow SSC/c out of the voltage source,
`
with

`The impedance is computed to provide an apparent power flow SSC/c out of the voltage source, `
or, in case it is acceptable to omit c:
`The impedance is computed to provide an apparent power flow SSC out of the voltage source, `
 Regards.

**Comment by AndreaBartolini** [comment]
I agree with the proposal to remove the `parameter c` from the model. 
This does not preserve the back-compatibility of the library if the user had modified said parameter but, according to the to-do list proposed in https://github.com/PowerGrids/PowerGrids/issues/39, the back-compatibility will still be lost after the scheduled convertion to MSL 4.0.0.

**Comment by AndreaBartolini** [comment]
solved by PR https://github.com/PowerGrids/PowerGrids/pull/57
