### ISSUE TITLE
Initialization coordination issues

### ISSUE THREAD

**Issue by max-privato** [PowerGrids/PowerGrids#50]
Consider a typical case of a line connected to busses at its terminals.
Powergrids allows defining the initial value of voltage magnitude and angle for both bus and line terminal. But what value will be used for actual initialisation (obviously the two values must necessarily be equal)? The user does not know and gets confused. 

Active and reactive power flows share this issue: two components connected together must have initial powers such that their sum is zero, and similar requirements occur in the case of multiple connections.

A possibility to solve this redundancy is to add a flag in the masks for each initial value (voltage amplitude, voltage phase, active and reactive power) possibly named "use this value". 
So, in case of a bus connecting n nodes, the user can set (at most) n-1 active and reactive powers and one voltage amplitude and phase, leaving the "use this value" unchecked for the remaining items.

I said "at most", since in several cases PowerGrids can be able to solve the initial problem even without having good initial values for, say, voltages for buses and line terminals. 

For compatibility with the present behaviour, I would leave it possible also to set _all_ voltages and powers; in this case, as it is today, it is highly advisable that the values be consistent, e.g. the voltage magnitude of all terminals connected together be _exactly_ equal to each other.

**A later note.** 
This issue message assumes that initialization data for lines play an important role in the initialization of PowerGrids network.
This is not totally granted since in the IEEE14bus example all terminal line initialization data are left to their default values (voltages and active powers to their nominals, reactive powers and voltage angles to zero). 

However, once it is decided to let the user define these initial values, they must be consistent. This justifies this ticket.

**Comment by casella** [comment]
Issues addressed in PowerGrids 2.0.0
