### ISSUE TITLE
One of the line terminals has disappeared

### ISSUE THREAD

**Issue by casella** [PowerGrids/PowerGrids#73]
@ceraolo reports:

What happended to line terminals?

One of the two terminals now has disappeared, probaly as a consequence of some mistake made in PR #46.

Here's what is see on IEEE 14 bus, based on the current situation as available in this ticket's  link: https://github.com/PowerGrids/PowerGrids/commits/Issue%2352_InvalidRootWhenSimulatingShortCircuitIEEE14:
![image](https://github.com/PowerGrids/PowerGrids/assets/7373030/dc000e25-88c4-44a8-ab44-3bac40833026)
Hers's what I expected, based on my  PRs 68 and 47:
![image](https://github.com/PowerGrids/PowerGrids/assets/7373030/59eb8e8e-6ac5-4c2f-a207-e998ae2b5edd)

**Comment by casella** [comment]
> One of the two terminals now has disappeared, probaly as a consequence of some mistake made in PR #46.

It's actually PR #68, PR #46 was abandoned.

**Comment by AndreaBartolini** [comment]
Strange behavior... it seems to be an OM problem. Herebelow what I see on my PC:
Without new instance API:
![immagine](https://github.com/PowerGrids/PowerGrids/assets/25974985/4bca6fa8-723f-4201-b19d-bffca5faa763)

With new instance API enabled:
![immagine](https://github.com/PowerGrids/PowerGrids/assets/25974985/d631d3bc-8e31-4e37-ac07-1f5acf739932)

This my actual position on GIT repo:
![immagine](https://github.com/PowerGrids/PowerGrids/assets/25974985/94bbc7c9-a59e-4f03-94cb-432332336bdd)


@casella to implement the feature I've used the following annotations:
```modelica
 extends TerminalAC annotation(IconMap(primitivesVisible=false), DiagramMap(primitivesVisible=false));
```
that as far as I know still have some problems... https://github.com/OpenModelica/OpenModelica/issues/5610

**Comment by AndreaBartolini** [comment]
With lower zoom level...
![immagine](https://github.com/PowerGrids/PowerGrids/assets/25974985/8bd14eea-5c34-48e5-8090-8313c4aabeef)


![immagine](https://github.com/PowerGrids/PowerGrids/assets/25974985/32320d17-e344-4f32-bd02-26a25c939c08)

**Comment by AndreaBartolini** [comment]
Here my OM version:
OpenModelica v1.22.0-dev-111-g16dbe81bb0 (64-bit)

**Comment by ceraolo** [comment]
Maybe it is an OM 1.20.0 issue.
OM 1.20.0 => terminals a missing
OM 1.22.0-dev-111=> terminals a visible
Dymola => terminals a  visible 
SImulationX => terminals a visible

**Comment by casella** [comment]
Regarding OMC, I would suggest to only test the library with the new instance-based interface. This is what will be used in the future, the old interface is going to be retired in 1.22.0. If there is anything wrong with the rendering with the new instance-based interface, please open tickets so we can get it fixed ASAP.
