### ISSUE TITLE
Boxed components should not be transparent.

### ISSUE THREAD

**Issue by ceraolo** [PowerGrids/PowerGrids#77]
Consider the following screenshot.
As you see, all MSL boxed components are not transparent, while many Powergrids' are.
Having transparent boxed components makes a bit more difficult to drag them with mouse movement.

I would recomment to fill all of them with white (I can issue a PR in case I'm requested to do so).
Also generator (and, possibly, transformer) circles, for me, should be filled with white.
Doing this for transformer is just slightly trickier, since it involves for one winding using two overlapped circles, the lower filled, the uper transparent.

![image](https://github.com/PowerGrids/PowerGrids/assets/7373030/04cb6370-522d-4903-9220-d59ff93d97ea)

**Comment by casella** [comment]
Good point, agreed on my side.

**Comment by AndreaBartolini** [comment]
I agree with the proposed change, and I suggest to do this at the end of the current work, together with the reshape of the diagrams in order to cover the entire blank field.

**Comment by AndreaBartolini** [comment]
Implemented by PR #134
